# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5edd3ec1a167631a12c0d68111667cb4d2ded5c5f125fd2da5087008e51214ed61f9a5c0244f09be57987f38339456b6484af693e5781ba1dfb8fa3de6c71c4e

test:
  secret_key_base: fe2439fe296d21cc7e4a6d742d931f1644f0032bded9b5b345d67c13fc7264abf2fd7a01d621c4fcfe549578b41bec14f2fc12b679ab030cceab6a9e6ff86e8c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
